version: '3.9'

services:
  postgres:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=scott
      - POSTGRES_PASSWORD=tiger
      - POSTGRES_DB=finance